export interface CatBreed {
  id: string;
  name: string;
  alt_names?: string;
  description: string;
  cfa_url?: string;
  vetstreet_url?: string;
  vcahospitals_url?: string;
  wikipedia_url?: string;
  reference_image_id?: string;
  origin: string;
  country_codes: string;
  country_code: string;
  life_span: string;
  temperament: string;
  indoor: number;
  lap: number;
  experimental: number;
  hairless: number;
  natural: number;
  rare: number;
  rex: number;
  suppressed_tail: number;
  short_legs: number;
  hypoallergenic: number;
  adaptability: number;
  affection_level: number;
  child_friendly: number;
  dog_friendly: number;
  energy_level: number;
  grooming: number;
  health_issues: number;
  intelligence: number;
  shedding_level: number;
  social_needs: number;
  stranger_friendly: number;
  vocalisation: number;
}
  